name="cursed-graphics"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-23"
account_id = "ddc0f8101374c7bf29ab528eefc435ec"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "cursed-graphics"
preview_bucket_name = "cursed-graphics"

[build]
# cargo install worker-build
command = "worker-build --release"
