name="cursed-graphics"
main = "build/worker/shim.mjs"
compatibility_date = "2024-11-23"

kv_namespaces = [
  { binding = "NAME_MAP", id = "12226ae0f2fd4038ba15059d130f969e", preview_id = "12226ae0f2fd4038ba15059d130f969e" }
]

[build]
command = "cargo install worker-build && worker-build --release"
